#!/bin/sh

#source var/function
. ./function.sh
inst_launch_workaround

PATH=./:$PATH
print_start() {
  #    more << EOF
  echo "Iniciando spAthena..."
  echo "            (c) 2013 Proyecto spAthena"
  echo ""
  echo ""
  echo "comprobando..."
  #EOF
}

get_status(){
   PIDFILE=.$1.pid
   if [ -e ${PIDFILE} ]; then
    ISRUN=$(ps ax | grep $(cat ${PIDFILE}) | grep $1)
    PSRUN=$(echo "$ISRUN" | awk '{ print substr( $0, 0, 7) }')
   fi
   return $PSRUN
}

#cheking if already started, launch and mark in log
start_serv(){ 
  LOGFILE="log/$1.log"
  get_status $1
  echo "My logfile=${LOGFILE}"
  if [ -z ${PSRUN} ]; then
    exec ./$1&
    echo $! > .$1.pid
    echo "Servidor '$1' iniciado a `date +"%m-%d-%H:%M-%S"`"
    echo "Servidor '$1' iniciado a `date +"%m-%d-%H:%M-%S"`" >> ${LOGFILE}
  else
    echo "Imposible iniciar '$1', porque ya se ha iniciado p${PSRUN}"
    echo "Imposible iniciar '$1', porque ya se ha iniciado p${PSRUN}" >> ${LOGFILE}
  fi
}

#experimental
watch_serv(){
  LOGFILE=./log/$1.log
  ulimit -Sc unlimited

  while true; do
   get_status $1
   if [ -z ${PSRUN} ]; then
     $count=$count+1
     echo "servidor '$1' esta caido" >> ${LOGFILE}
     echo "reiniciando servidor a `date +"%m-%d-%H:%M-%S"`">> ${LOGFILE}
     exec ./$1&
     echo $! > .$1.pid   
     if [ $3 ] && [ $3 -lt $count ]; then break; fi
   else sleep $2    
   fi
  done
}

restart(){
  $0 stop
  for i in ${L_SRV} ${C_SRV} ${M_SRV}
    do
    while true; do
	get_status ${i}
	if [ ${PSRUN} ]; then echo "'${i}' todavia esta funcionando p${PSRUN} esperando a que se cierre"; sleep 2;
        else break; fi
    done
  done
  $0 start
}

case $1 in
    'start')
        print_start
        check_files
	echo "Comprobacion completada."
	echo "Parece estar bien!"
	for i in ${L_SRV} ${C_SRV} ${M_SRV}
	    do
		start_serv $i
	    done
        echo "Iniciando spAthena ahora."
;;
    'watch')
	for i in ${L_SRV} ${C_SRV} ${M_SRV}
	    do		
		watch_serv $i 10 3
	    done
 	echo "Viendo spAthena."
;;	
    'stop')
	for i in ${L_SRV} ${C_SRV} ${M_SRV}
	    do
		PIDFILE=.${i}.pid
		if [ -e ./${PIDFILE} ]; then
		    kill $(cat ${PIDFILE})
		    rm ${PIDFILE}
		fi
	    done
;;
    'restart')
         restart
;;
    'status')
	for i in ${L_SRV} ${C_SRV} ${M_SRV}
	do
		get_status ${i}
		if [ ${PSRUN} ]; then echo "'${i}' esta funcionando p${PSRUN}"; else echo "'${i}' esta caido"; fi
	done
;;	
    *)
        echo "Usage: athena-start { start | stop | restart | status | watch }"
        read -p "Enter a valid option: " readEnterKey
		$0 $readEnterKey
;;
esac


